apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeinvaders
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: kubeinvaders
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata: {}
    spec:
      containers:
      - image: luckysideburn/kubeinvaders:latest
        imagePullPolicy: Always
        name: kubeinvaders
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        envFrom:
        - configMapRef:
            name: kubeinvaders-config
        env:
        - name: ROUTE_HOST
          value: $(ROUTE_HOST)
        - name: NAMESPACE
          value: $(TARGET_NAMESPACE)
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: kubeinvaders-token
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
