apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeinvaders
resources:
- source-vars.yaml
- namespace.yaml
- service-account.yaml
- token.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
commonLabels:
  app.kubernetes.io/name: kubeinvaders
images:
- name: luckysideburn/kubeinvaders:latest
  newName: luckysideburn/kubeinvaders
  newTag: latest
vars:
- fieldref:
    fieldPath: data.MY_NAMESPACE
  name: MY_NAMESPACE
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: source-vars
- fieldref:
    fieldPath: data.ROUTE_HOST
  name: ROUTE_HOST
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: source-vars
- fieldref:
    fieldPath: data.TARGET_NAMESPACE
  name: TARGET_NAMESPACE
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: source-vars
configurations:
- kustomize-config.yaml
configMapGenerator:
- name: kubeinvaders-config
  env: config.txt
