kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeinvaders
  labels:
    app.kubernetes.io/name: kubeinvaders
subjects:
- kind: ServiceAccount
  name: kubeinvaders
  namespace: $(MY_NAMESPACE)
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeinvaders